### ISSUE TITLE
[bug] new bug

### ISSUE THREAD

**Issue by Willtom999** [ItsMax123/StaffMode#14]
The ban player Is internal error

**Comment by ItsMax123** [comment]
Yes, StaffMode is no longer updated for the time being.

**Comment by Willtom999** [comment]
because?

**Comment by ItsMax123** [comment]
This was the first complex plugin I did on pocketmine and it was more of a learning project than an actual good product. I am now working on other projects which take up all the time that school doesn't consume. When I have more time on my hands I will *maybe* update & maintain the plugin. But in order to fix it. I will most likely need to re-make everything from scratch as the quality of the code is very bad.
